cmd_/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.o := arm-poky-linux-gnueabi-gcc -Wp,-MD,/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /opt/poky/1.4.4/sysroots/x86_64-pokysdk-linux/usr/lib/armv5te-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.7.2/include -I/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/include/uapi -Iinclude/generated/uapi -include /home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-nuc970/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -Os -Wno-maybe-uninitialized -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -marm -D__LINUX_ARM_ARCH__=5 -march=armv5te -mtune=arm9tdmi -msoft-float -Uarm -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=7601U -DRESOURCE_PRE_ALLOC -I/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/include -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DSTATS_COUNT_SUPPORT -DMT7601U -DMT7601 -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRX_DMA_SCATTER -DVCORECAL_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DRTMP_INTERNAL_TX_ALC -DCONFIG_ANDES_SUPPORT -DDPD_CALIBRATION_SUPPORT -DCONFIG_RX_CSO_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT -I/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/include  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7601Usta)" -c -o /home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.o /home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.c

source_/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.o := /home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.c

deps_/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \

/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.o: $(deps_/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.o)

$(deps_/home/elinux/Gokul_Project/7510BuildSystem-TNSTC-NewAPI/Kernel/wifi_mt7601u/os/linux/../../rate_ctrl/alg_ags.o):
